# Generated by Django 4.1.3 on 2023-03-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_saving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='saving',
        ),
        migrations.RemoveField(
            model_name='post',
            name='views_number',
        ),
    ]
