# Generated by Django 4.1.3 on 2023-03-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='blog/static/img/default.jpeg', height_field=650, max_length=200, upload_to='blog/static/img', verbose_name='Картинка для поста', width_field=413),
        ),
    ]
