# Generated by Django 4.1.3 on 2023-04-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_comment_author_alter_comment_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parallax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='parallax.jpg', upload_to='blog/static/img/parallax', verbose_name='Зображення головної')),
            ],
        ),
    ]
