# Generated by Django 4.1.3 on 2023-04-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_parallax'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parallax',
        ),
    ]
