# Generated by Django 4.1.3 on 2023-04-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
