# Generated by Django 5.1.5 on 2025-02-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_post_text_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='images/', verbose_name='Зображення категорії'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='images/default.jpg', max_length=200, upload_to='images/', verbose_name='Картинка для поста'),
        ),
    ]
